<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1Cr2DBN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1Cr2DBN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1Cr2DBN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1Cr2DBN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container1Cr2DBN\App_KernelDevDebugContainer([
    'container.build_hash' => '1Cr2DBN',
    'container.build_id' => 'bb648cd8',
    'container.build_time' => 1634730042,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1Cr2DBN');
